job_portal/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from job import views
from job.views import JobDetailView, JobView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',views.register,name='register'),
    path('',views.user_login, name = 'user_login'),
    path('logout/', views.user_logout , name = 'logout'),
    path('job_view/',views.job_view, name = 'job'),
    path('job/<int:pk>/', JobDetailView.as_view(), name='job_detail'),
    path('form/', JobView.as_view(), name = 'jobform'),
    path('index/',views.index, name ='index'),
    path('form_upload/', views.applicant_form_upload, name = 'form_upload')
]

if settings.DEBUG:
    urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

job/models.py
from django.db import models
#from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify


JOB_TYPE = (
    ('Full time', "Full time"),
    ('Part time', "Part time"),
    ('Internship', "Internship"),
)

CHOICES = (
        ('Mumbai', 'Mumbai'),
        ('Delhi', 'Delhi'),
        ('Bangalore', 'Bangalore'),
        ('Hyderabad', 'Hyderabad'),
        ('Chennai', 'Chennai'),
        ('Jaipur', 'Jaipur'),
        ('Bhopal', 'Bhopal'),
        ('Patna', 'Patna'),

    )
class Job(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    skills = models.TextField()
    company = models.CharField(max_length=200)
    city = models.CharField(max_length=50, choices = CHOICES ,blank = True)
    description = models.TextField(blank = True)
    job_type = models.CharField(max_length=50, choices = JOB_TYPE ,blank = True)
    post_date = models.DateTimeField(auto_now_add = True, blank = True)
    about_job = models.TextField(blank = True)
    photo = models.FileField(blank = True)
    # slug = models.SlugField(unique = True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.company)
        super(Job, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.title


class Applicant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    document = models.FileField(upload_to='media/files')

    def __str__(self):
        return self.user.email

job/forms.py
from django import forms
from django.contrib.auth.models import User
from job.models import * 


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password',]

class JobForm(forms.ModelForm):

    class Meta:
        model = Job
        exclude = ('slug',)
        
class ApplicantForm(forms.ModelForm):
    """Form definition for Applicant."""

    
    # def __init__(self, *args, **kwargs):
    #     self.user_id = kwargs.pop('user_id')
    #     super(ApplicantForm, self).__init__(*args, **kwargs)

    class Meta:
        """Meta definition for Applicantform."""

        model = Applicant
        fields = ('document',)

job/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from job.forms import ApplicantForm, JobForm, UserForm
from django.contrib.auth.decorators import login_required
from job.models import Job
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView

# Create your views here.

def index(request):
    return render(request, 'index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        print("post")
        user_form = UserForm(data = request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user = user.save()
            return HttpResponseRedirect(reverse('index'))
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render(request,'registration.html',{'user_form':user_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username, password=password)
        
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password:{}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request,'login.html')

def job_view(request):
    job_list = Job.objects.all()
    return render(request,'job_list.html',{'jobs':job_list})


class JobDetailView(DetailView):

    model = Job
    template_name = 'job_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class JobView(FormView):
    template_name = 'form.html'
    form_class = JobForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        return super().form_valid(form)

def applicant_form_upload(request):
    if request.method == 'POST':
        form = ApplicantForm(request.POST, request.FILES)
        if form.is_valid():
            # import pdb; pdb.set_trace()
            applicant_form = form.save(commit=False)
            applicant_form.user = request.user
            applicant_form.save()
        
            
            return redirect('index')
    else:
        form = ApplicantForm()
    return render(request, 'file_upload_form.html',{'form':form})

job/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-md bg-dark navbar-dark">

    <!-- Brand -->
    <a class = "navbar-brand" href="#">Micropyramid</a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class = "collapse navbar-collapse">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'index' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'job' %}">All Jobs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin Login</a>

            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class = "nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class = "nav-link" href="{% url 'user_login' %}">Login</a>
                </li>
            {% endif %}

        </ul>
    </div>
  </nav>
<br>
<div>
    {% block body_block %}
    {% endblock  %}
</div>

</body>
</html>

job/templates/file_upload_form.html
{% extends 'base.html' %}

{% block body_block %}
    <body>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>
        <p><a href = "{% url 'index' %}">Return to home</a></p>
    </body>
    
{% endblock %}

job/templates/form.html
<tr>
    <th><label for="id_user">User:</label></th>
    <td><select name="user" required id="id_user">\n <option value="" selected>---------</option>\n\n <option value="1">
                admin</option>\n\n <option value="2">sathwik</option>\n\n <option value="3">dinesh</option>\n\n <option
                value="4">manoj</option>\n\n</select></td>
</tr><br><tr>
    <th><label for="id_title">Title:</label></th>
    <td><input type="text" name="title" maxlength="300" required id="id_title"></td>
</tr><br><tr>
    <th><label for="id_skills">Skills:</label></th>
    <td><textarea name="skills" cols="40" rows="10" required id="id_skills">\n</textarea></td>
</tr><br><tr>
    <th><label for="id_company">Company:</label></th>
    <td><input type="text" name="company" maxlength="200" required id="id_company"></td>
</tr><br><tr>
    <th><label for="id_city">City:</label></th>
    <td><select name="city" id="id_city">\n <option value="" selected>---------</option>\n\n <option value="mb">Mumbai
            </option>\n\n <option value="dl">Delhi</option>\n\n <option value="bl">Bangalore</option>\n\n <option
                value="hy">Hyderabad</option>\n\n <option value="cn">Chennai</option>\n\n <option value="jp">Jaipur
            </option>\n\n <option value="bp">Bhopal</option>\n\n <option value="pn">Patna</option>\n\n</select></td>
</tr><br><tr>
    <th><label for="id_description">Description:</label></th>
    <td><textarea name="description" cols="40" rows="10" id="id_description">\n</textarea></td>
</tr><br><tr>
    <th><label for="id_job_type">Job type:</label></th>
    <td><select name="job_type" id="id_job_type">\n <option value="" selected>---------</option>\n\n <option value="1">
                Full time</option>\n\n <option value="2">Part time</option>\n\n <option value="3">Internship</option>
            \n\n</select></td>
</tr><br><tr>
    <th><label for="id_about_job">About job:</label></th>
    <td><textarea name="about_job" cols="40" rows="10" id="id_about_job">\n</textarea></td>
</tr><br><tr>
    <th><label for="id_photo">Photo:</label></th>
    <td><input type="file" name="photo" id="id_photo"></td>
</tr>

job/templates/index.html
{% extends "base.html" %}
{% block body_block %}

<div class="container">
    <div class = "jumbotron">
        <h1>Welcome to the Micropyramid Job Portal</h1>
        {% if user.is_authenticated %}
            <h2>Hello {{ user.username }}</h2>
        {% else %}
            <h3><font color = "blue">Register or Login if you'd like to</font></h3>
        {% endif %}
    
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic cumque, tempore placeat quo quasi nihil, quia fuga deserunt eum, libero maiores aliquid! Nam quae nemo aperiam necessitatibus quasi quidem voluptatum.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Distinctio sunt inventore ut reiciendis voluptas ullam consequuntur aliquam tempore adipisci molestiae, quam illum, hic temporibus atque quae nostrum, illo doloremque assumenda?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit aut, sunt inventore alias accusamus veniam quaerat reiciendis sed ex ullam. Eaque corporis, quisquam sint veniam doloremque delectus voluptas molestiae eos.</p>
    </div>
</div>
{% endblock %}

job/templates/job_detail.html
{% extends "base.html" %}
{% block body_block %}
<body>
    

<table class="table">
    <!-- <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        
      </tr>
    </thead> -->
    <tbody>
      <tr>
        <!-- <th scope="row">1</th> -->
        <td>Job Title</td>
        <td>{{ object.title }}</td>
        
      </tr>
      <tr>
        <!-- <th scope="row">2</th> -->
        <td>Job Skills</td>
        <td>{{ object.skills }}</td>
        
      </tr>
      <tr>
        <!-- <th scope="row">3</th> -->
        <td>Job Company</td>
        <td>{{ object.company }}</td>
        
      </tr>
      <tr>
        <!-- <th scope="row">3</th> -->
        <td>Job City</td>
        <td>{{ object.city }}</td>
        
      </tr>
      <tr>
        <!-- <th scope="row">3</th> -->
        <td>Job Type</td>
        <td>{{ object.job_type }}</td>
        
      </tr>
      <tr>
        <!-- <th scope="row">3</th> -->
        <td>Job Post Date</td>
        <td>{{ object.post_date|date }}</td>
        
      </tr>
      <tr>
        <!-- <th scope="row">3</th> -->
        <td>About Job</td>
        <td>{{ object.about_job }}</td>
        
      </tr>
      
    </tbody>
  </table>
  <h3><a href="{% url 'form_upload' %}">Upload Your Resume Here</a></h3>
</body>
{% endblock  %}





<!-- <p>Job_Title:{{ object.title }}</p>
<p>Job_Skills:{{ object.skills }}</p>
<p>Job_Company: {{ object.company }}</p>

<p>Job_City:{{ object.post_date|date }}</p>
<p>Job_Type: {{ object.type }}</p>
<p>About_Job:{{ object.about_job }}</p> -->

job/templates/job_list.html
{% extends "base.html" %}
{% block body_block %}
<body>
    {% if jobs %}
        
            
            
        {% for job in jobs %}
            <table class = table>
                <tr>
                    <td>
                        <a href="{% url 'job_detail' job.id %}">{{ job.company }}</a>
                    </td>
                    <td>{{ job.description }}</td>
                    
            
                    </td>
                </tr>
            </table>
        {% endfor %}
    {% endif %}
</body>
{% endblock  %}

<tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>

job/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
    <div class = "container">
        <div class = "jumbotron">
            <h1>Login here :</h1>
            <form  method = "post" action="{% url 'user_login' %}">
                {% csrf_token %}
                {# A more "HTML" way of creating the login form #}
                <label for="username">Username:</label>
                <input type="text" name = "username" placeholder = "Username">
                <label for="password">Password:</label>
                <input type="password" name="password" placeholder = "Password">
                <input type="submit" name="" value="Login">

            </form>
            <p>if not registered</p>
            <a href="{% url 'register' %}"><button>Register</button></a>
            
        </div>
    </div>
{% endblock %}

job/templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body_block %}
    <div class = "container">
        <div class = "jumbotron">
            {% if registered %}
                <h1>Thank you for registering!</h1>
            {% else %}
                <h1>Register Here</h1>
                <h3>Just fill out the form.</h3>
            <form enctype = "multipart/form-data" method= "POST">
            {% csrf_token %}
            {{ user_form.as_p }}
           <input type="submit" name="" value = "Register">

            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}